### ISSUE TITLE
Error building www

### ISSUE THREAD

**Issue by frantic0** [vaheqelyan/svelte-grid#49]
Hi, 

I'm trying to build the latest version of the www examples (with dev, build scripts) but unsuccessful with this type of error:

`[!] Error: Could not resolve '../../components/svelte-grid/index.svelte' from src/routes/examples/min_max.svx
Error: Could not resolve '../../components/svelte-grid/index.svelte' from src/routes/examples/min_max.svx
    at error (/Users/francisco/Documents/dev/MIMIC/svelte-grid-upstream/www/node_modules/rollup/dist/shared/rollup.js:5251:30)
    at ModuleLoader.handleResolveId (/Users/francisco/Documents/dev/MIMIC/svelte-grid-upstream/www/node_modules/rollup/dist/shared/rollup.js:18389:24)
    at /Users/francisco/Documents/dev/MIMIC/svelte-grid-upstream/www/node_modules/rollup/dist/shared/rollup.js:18358:22
    at async Promise.all (index 1)
    at async ModuleLoader.fetchStaticDependencies (/Users/francisco/Documents/dev/MIMIC/svelte-grid-upstream/www/node_modules/rollup/dist/shared/rollup.js:18356:34)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchModule (/Users/francisco/Documents/dev/MIMIC/svelte-grid-upstream/www/node_modules/rollup/dist/shared/rollup.js:18333:9)
    at async /Users/francisco/Documents/dev/MIMIC/svelte-grid-upstream/www/node_modules/rollup/dist/shared/rollup.js:18306:48
    at async Promise.all (index 7)
    at async ModuleLoader.fetchDynamicDependencies (/Users/francisco/Documents/dev/MIMIC/svelte-grid-upstream/www/node_modules/rollup/dist/shared/rollup.js:18296:30)`

svelte-grid isn't in '../../components/svelte-grid/index.svelte'.

I am missing anything? 

Thanks,
F

**Comment by vaheqelyan** [comment]
This is because this path is ignored

**Comment by vaheqelyan** [comment]
i'll try to make it read from the original `src/`. there was also a time when I installed svelte-grid using `npm`

**Comment by vaheqelyan** [comment]
Unfortunately I couldn't do it, If you want to build `www/` you should move `src/*` to `components/svelte-grid`

**Comment by frantic0** [comment]
thanks
