### ISSUE TITLE
Error with latest svelte-grid in Sapper.

### ISSUE THREAD

**Issue by michaelcuneo** [vaheqelyan/svelte-grid#56]
The new version of svelte-grid is giving me the following error in Sapper.

```
webpack:///./node_modules/svelte-grid/src/index.svelte?:1
throw new Error("Module parse failed: Unexpected token (134:36)\nFile was processed with these loaders:\n * ./node_modules/svelte-loader/index.js\nYou may need an additional loader to handle the result of these loaders.\n| \t\t\tid: item.id,\n| \t\t\tindex: i,\n> \t\t\tresizable: item[getComputedCols]?.resizable,\n| \t\t\tdraggable: item[getComputedCols]?.draggable,\n| \t\t\txPerPx,");
^

Error: Module parse failed: Unexpected token (134:36)
File was processed with these loaders:
 * ./node_modules/svelte-loader/index.js
You may need an additional loader to handle the result of these loaders.
```

**Comment by vaheqelyan** [comment]
Interesting, I built `/www` with the latest svelte and sapper version.. I see you are using webpack... 
Could you show me your configuration (webpack) file please ? I need to reproduce it

**Comment by michaelcuneo** [comment]
```
const webpack = require('webpack');
const WebpackModules = require('webpack-modules');
const path = require('path');
const config = require('sapper/config/webpack.js');
const pkg = require('./package.json');

const mode = process.env.NODE_ENV;
const dev = mode === 'development';

const alias = { svelte: path.resolve('node_modules', 'svelte') };
const extensions = ['.mjs', '.js', '.json', '.svelte', '.html'];
const mainFields = ['svelte', 'module', 'browser', 'main'];
const fileLoaderRule = {
	test: /\.(png|webp|svg|jpe?g|gif)$/i,
	use: [
		'file-loader',
	]
};

module.exports = {
	client: {
		entry: config.client.entry(),
		output: config.client.output(),
		resolve: { alias, extensions, mainFields },
		module: {
			rules: [
				{
					test: /\.(svelte|html)$/,
					use: {
						loader: 'svelte-loader',
						options: {
							dev,
							hydratable: true,
							hotReload: true // pending https://github.com/sveltejs/svelte/issues/2377
						}
					}
				},
				fileLoaderRule
			]
		},
		mode,
		plugins: [
			// pending https://github.com/sveltejs/svelte/issues/2377
			// dev && new webpack.HotModuleReplacementPlugin(),
			new webpack.DefinePlugin({
				'process.browser': true,
				'process.env.NODE_ENV': JSON.stringify(mode)
			}),
		].filter(Boolean),
		devtool: dev && 'inline-source-map'
	},

	server: {
		entry: config.server.entry(),
		output: config.server.output(),
		target: 'node',
		resolve: { alias, extensions, mainFields },
		externals: Object.keys(pkg.dependencies).concat('encoding'),
		module: {
			rules: [
				{
					test: /\.(svelte|html)$/,
					use: {
						loader: 'svelte-loader',
						options: {
							css: false,
							generate: 'ssr',
							hydratable: true,
							dev
						}
					}
				},
				fileLoaderRule
			]
		},
		mode,
		plugins: [
			new WebpackModules()
		],
		performance: {
			hints: false // it doesn't matter if server.js is large
		}
	},

	serviceworker: {
		entry: config.serviceworker.entry(),
		output: config.serviceworker.output(),
		mode
	}
};
```

**Comment by vaheqelyan** [comment]
ok, used this template https://github.com/sveltejs/template-webpack, 
here is the result
![image](https://user-images.githubusercontent.com/14107127/100378826-4be6a380-302d-11eb-8e2c-deb44929e444.png)
I probably exported my component incorrectly, :thinking:

**Comment by vaheqelyan** [comment]
![image](https://user-images.githubusercontent.com/14107127/100379279-0c6c8700-302e-11eb-8ba7-d7e4f4618089.png)
don't know what could be wrong with this line

**Comment by evdama** [comment]
Hi guys, I'm using rollup but then something is off here as well... I'm not entirely sure yet what as I haven't started to dig into yet but here's what I know so far

- local development works as I'm using rollup with my Sapper app
- for deployment I'm on firebase, there I use an SSR function that's basically a firebase cloud function which is where my deployemnt breaks with following errors

![Screen Shot 2020-11-26 at 18 31 37](https://user-images.githubusercontent.com/39374084/100380004-3fa31c00-3016-11eb-9624-e5b094e71e22.png)

Note the orange rectangle... this made me look for where this code is within my app and it turns out it's from svelte-grid. No clue yet what's happening and why but I thought I provide the info as this might be related to the OPs issue.

**Comment by vaheqelyan** [comment]
Oh no

**Comment by vaheqelyan** [comment]
tracking https://github.com/sveltejs/svelte-loader/issues/143

**Comment by vaheqelyan** [comment]
I think the problem comes from  `svelte-loader`. I can create www/ without any errors ( even though i use rollup )

**Comment by evdama** [comment]
Yeah, probably, I'll take a look at the issues there after dinner, maybe I find some infos that could help resolve things because my firebase cloud function logs also mention the loader 😋

**Comment by evdama** [comment]
It's the optional chaining operator because adding https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining to my client and server sections of my rollup config made my errors go away

```js
      babel( {
        extensions: [ '.js', '.mjs', '.html', '.svelte' ],
        runtimeHelpers: true,
        exclude: [ 'node_modules/@babel/**' ],
        presets: [
          [
            '@babel/preset-env',
            {
              targets: '> 0.25%, not dead',
            },
          ],
        ],
        plugins: [
          '@babel/plugin-syntax-dynamic-import',
          '@babel/plugin-proposal-optional-chaining',
          [
            '@babel/plugin-transform-runtime',
            {
              useESModules: true,
            },
          ],
        ],
      } ),
```

**Comment by benwoodward** [comment]
I just ran into this running `rollup --config`: 

```javascript
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
node_modules/svelte-grid/build/index.mjs (453:18)
451:     ...items.map((val) => {
452:       const item = val[cols];
453:       return item?.y + item?.h;
                       ^
454:     }),
455:     1,
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/Users/ben/.asdf/installs/nodejs/12.10.0/.npm/lib/node_modules/rollup/dist/shared/rollup.js:10120:30)
    at Module.error (/Users/ben/.asdf/installs/nodejs/12.10.0/.npm/lib/node_modules/rollup/dist/shared/rollup.js:14557:16)
    at tryParse (/Users/ben/.asdf/installs/nodejs/12.10.0/.npm/lib/node_modules/rollup/dist/shared/rollup.js:14450:23)
    at Module.setSource (/Users/ben/.asdf/installs/nodejs/12.10.0/.npm/lib/node_modules/rollup/dist/shared/rollup.js:14839:33)
    at /Users/ben/.asdf/installs/nodejs/12.10.0/.npm/lib/node_modules/rollup/dist/shared/rollup.js:16713:20
```

**Comment by evdama** [comment]
> EDIT: For reference, this issue was resolved for me by upgrading Rollup, see here: [rollup/rollup#3469](https://github.com/rollup/rollup/issues/3469)

That link says rollup 2.11 and above should have support for optional chaining but then I'm on latest 2.33.3 and still, without the babel snippet from above, it breaks my app deployment... hm... 🤔

**Comment by evdama** [comment]
Also, even with my added code snippet to rollup conf for optional chaining as seen above, the inital errors are back 🤷

![Screen Shot 2020-11-27 at 12 39 17](https://user-images.githubusercontent.com/39374084/100445692-d242ca00-30ad-11eb-840e-68013e044d22.png)

**Comment by vaheqelyan** [comment]
@michaelcuneo For the webpack https://github.com/sveltejs/svelte-loader/issues/137#issuecomment-706750871, this may be the solution to the problem (it works at least for me)

For rollup everything works fine

**Comment by vaheqelyan** [comment]
> > EDIT: For reference, this issue was resolved for me by upgrading Rollup, see here: [rollup/rollup#3469](https://github.com/rollup/rollup/issues/3469)
> That link says rollup 2.11 and above should have support for optional chaining but then I'm on latest 2.33.3 and still, without the babel snippet from above, it breaks my app deployment... hm... 🤔

this is taken from https://github.com/vaheqelyan/svelte-grid/blob/master/www/package.json

rollup
```json
    "@rollup/plugin-babel": "^5.2.1",
    "@rollup/plugin-commonjs": "^16.0.0",
    "@rollup/plugin-node-resolve": "^10.0.0",
    "@rollup/plugin-replace": "^2.3.4",
    "rollup": "^2.33.3",
    "rollup-plugin-glob": "^1.0.2",
    "rollup-plugin-svelte": "^6.1.1",
    "rollup-plugin-terser": "^7.0.2",
```
babel
```json
    "@babel/core": "^7.12.8",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/plugin-transform-runtime": "^7.12.1",
    "@babel/preset-env": "^7.12.7",
    "@babel/runtime": "^7.12.5",
```

**Comment by evdama** [comment]
svelte-grid with rollup doesn't work for me, fails with afore mentioned erros shown in the screenshots above. Here is my relevant `rollup` and `babel` packages

```sh
sa@m1-mini: ~/0/edm  |master U:3 ✗| alias gr; gr rollup package.json
alias gr='grep -rni --color'
package.json:20:    "@rollup/plugin-babel": "^5.2.1",
package.json:21:    "@rollup/plugin-commonjs": "^16.0.0",
package.json:22:    "@rollup/plugin-json": "^4.1.0",
package.json:23:    "@rollup/plugin-node-resolve": "^10.0.0",
package.json:24:    "@rollup/plugin-replace": "^2.3.4",
package.json:25:    "@rollup/plugin-typescript": "^6.1.0",
package.json:73:    "rollup": "^2.33.3",
package.json:74:    "rollup-plugin-auto-external": "^2.0.0",
package.json:75:    "rollup-plugin-json": "^4.0.0",
package.json:76:    "rollup-plugin-node-builtins": "^2.1.2",
package.json:77:    "rollup-plugin-node-globals": "^1.4.0",
package.json:78:    "rollup-plugin-postcss": "^3.1.8",
package.json:79:    "rollup-plugin-svelte": "^7.0.0",
package.json:80:    "rollup-plugin-terser": "^7.0.2",
package.json:81:    "rollup-plugin-visualizer": "^4.2.0",
sa@m1-mini: ~/0/edm  |master U:4 ✗| gr babel package.json
package.json:12:    "@babel/core": "^7.12.9",
package.json:13:    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
package.json:14:    "@babel/plugin-transform-runtime": "^7.12.1",
package.json:15:    "@babel/preset-env": "^7.12.7",
package.json:16:    "@babel/runtime": "^7.12.5",
package.json:20:    "@rollup/plugin-babel": "^5.2.1",
package.json:42:    "babel-eslint": "^10.1.0",
sa@m1-mini: ~/0/edm  |master U:3 ✗|
```

**Comment by vaheqelyan** [comment]
You get something like this ?
```
TypeError: App.render is not a function
    at /home/vahe/Desktop/svelte-grid/www/__sapper__/dev/server/server.js:10871:49
    at Generator.next (<anonymous>)
    at fulfilled (/home/vahe/Desktop/svelte-grid/www/__sapper__/dev/server/server.js:6314:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by evdama** [comment]
No, my error messages when I run my deploy command are as in the screenshot above on the server side (read firebase deploy) and on the local shell I get this output:

```sh
=== Deploying to 'foo-dt3d0'...

i  deploying storage, firestore, functions, hosting
Running command: node predeploy.js
✔  functions: Finished running predeploy script.
i  firebase.storage: checking config/storage.rules for compilation errors...
⚠  [W] 40:10 - Unused function: lessThanOrEqualToNMegaBytes.
⚠  [W] 40:50 - Invalid variable name: request.
⚠  [W] 41:10 - Unused function: lessThanOrEqualToNGigaBytes.
⚠  [W] 41:50 - Invalid variable name: request.
⚠  [W] 45:10 - Unused function: isImage.
⚠  [W] 45:30 - Invalid variable name: request.
✔  firebase.storage: rules file config/storage.rules compiled successfully
i  firestore: reading indexes from config/firestore.indexes.json...
i  cloud.firestore: checking config/firestore.rules for compilation errors...
✔  cloud.firestore: rules file config/firestore.rules compiled successfully
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
✔  functions: required API cloudfunctions.googleapis.com is enabled
✔  functions: required API cloudbuild.googleapis.com is enabled
i  storage: uploading rules config/storage.rules...
i  firestore: latest version of config/firestore.rules already up to date, skipping upload...
✔  firestore: deployed indexes in config/firestore.indexes.json successfully
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (5.44 MB) for uploading
✔  functions: functions folder uploaded successfully
i  hosting[foo]: beginning deploy...
i  hosting[foo]: found 11 files in static
✔  hosting[foo]: file upload complete
✔  storage: released rules config/storage.rules to firebase.storage
✔  storage: released rules config/storage.rules to firebase.storage
✔  storage: released rules config/storage.rules to firebase.storage
✔  firestore: released rules config/firestore.rules to cloud.firestore
i  functions: updating Node.js 12 function setCustomClaimsOnEDMSignUp(us-central1)...
i  functions: updating Node.js 12 function setUserPropertiesOnEDMSignUp(us-central1)...
i  functions: updating Node.js 12 function ssr(us-central1)...
⚠  functions[setCustomClaimsOnEDMSignUp(us-central1)]: Deployment error.
Function failed on loading user code. Error message: Error: please examine your function logs to see the error cause: https://cloud.google.com/functions/docs/monitoring/logging#viewing_logs. Additional troubleshooting documentation can be found at https://cloud.google.com/functions/docs/troubleshooting#logging
⚠  functions[setUserPropertiesOnEDMSignUp(us-central1)]: Deployment error.
Function failed on loading user code. Error message: Error: please examine your function logs to see the error cause: https://cloud.google.com/functions/docs/monitoring/logging#viewing_logs. Additional troubleshooting documentation can be found at https://cloud.google.com/functions/docs/troubleshooting#logging
⚠  functions[ssr(us-central1)]: Deployment error.
Function failed on loading user code. Error message: Error: please examine your function logs to see the error cause: https://cloud.google.com/functions/docs/monitoring/logging#viewing_logs. Additional troubleshooting documentation can be found at https://cloud.google.com/functions/docs/troubleshooting#logging


Functions deploy had errors with the following functions:
	setCustomClaimsOnEDMSignUp
	setUserPropertiesOnEDMSignUp
	ssr


To try redeploying those functions, run:
    firebase deploy --only "functions:setCustomClaimsOnEDMSignUp,functions:setUserPropertiesOnEDMSignUp,functions:ssr"


To continue deploying other features (such as database), run:
    firebase deploy --except functions

Error: Functions did not deploy properly.
npm ERR! code 1
npm ERR! path /Users/sa/0/edm
npm ERR! command failed
npm ERR! command sh -c firebase deploy

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sa/.npm/_logs/2020-11-27T16_49_29_030Z-debug.log

> foo@0.1.0 bar:dev
> export GOOGLE_APPLICATION_CREDENTIALS="config/serviceAccount.js"; sapper dev

✔ server (24.2s)
✔ client (25.9s)
> Listening on http://localhost:3000
✔ service worker (603ms)```

**Comment by vaheqelyan** [comment]
https://github.com/vaheqelyan/svelte-grid/blob/37e842e52c24e844ab4f57ad92a17e83e17c1ea9/src/utils/other.js#L13
This line causes the pain ? but why,, :thinking:  i downgraded node to 10.x but the deployment does not fail

**Comment by vaheqelyan** [comment]
Well, I'll try to transpile correctly, after which you'll try it again.

**Comment by evdama** [comment]
No idea either but the usual suspects come to mind... different module formats and different ES versions in various combinations, layerd on top we have individal app setups with all kinds of bunder magic... one can only look forward to times when things will be more unified... Sveltekit and Snowpack I assume will already help in shrinking complexity on that part of our work 😇

For the particular issue I'm seeing with the combination of: Sapper, svelte-grid, firebase cloud functions I've today spend around 4 hours looking around and trying various things... all in vain... the only thing I can say for sure is that replacing `return item?.y + item?.h` with `return item && item.y + item && item.h` fixes things on my end 😋

**Comment by evdama** [comment]
> Well, I'll try to transpile correctly, after which you'll try it again.

I'm at a point where I'll try whatever you provide... except for the first round of Covid-19 vaxines 🤣

**Comment by vaheqelyan** [comment]
Patch version released,  `v3.1.1` i hope it won't throw an error

**Comment by evdama** [comment]
> Patch version released, `v3.1.1` i hope it won't throw an error

same exact error with 3.1.1

![Screen Shot 2020-11-27 at 22 06 48](https://user-images.githubusercontent.com/39374084/100484492-f24daa00-30fc-11eb-9179-9f15ba3b382d.png)

**Comment by vaheqelyan** [comment]
Can I see your full stack trace ?
![image](https://user-images.githubusercontent.com/14107127/100496771-34fc9a00-3170-11eb-9bfb-1ea5e2ef5267.png)

**Comment by vaheqelyan** [comment]
I thought that the problems arise because of this issue https://github.com/sveltejs/svelte/issues/4701

**Comment by evdama** [comment]
> Can I see your full stack trace ?
No, that's just about all the information I can see resp. that I found even when I went into the cloud logger and looked at what the cloud function deployments spit out.

**Comment by evdama** [comment]
> I thought that the problems arise because of this issue [sveltejs/svelte#4701](https://github.com/sveltejs/svelte/issues/4701)
Ok, hm... I understood this is mainly about using modern JS syntax in Svelte markup, which is something I don't do with optional chaining, that really, at least in my app, is only used in svelte-grid code at this point hence the entire dance I'm having/had... which is not to say I'm not super happy with this great great package and will of course continue to use it 😃

**Comment by vaheqelyan** [comment]
try to update the svelte-grid version.. `v3.3.1` (latest)

**Comment by evdama** [comment]
- v3.3.1 with my babel addition to the server section of the rollup.config.js file works (which is expected); this includes the entire CI chain including depoyment to live firebase site
- v3.3.1 without my babel addition to the server section (and therefore back to the original rollup.config.js version) of the rollup.config.js file works (which didn't work as seen above); this includes the entire CI chain including depoyment to live firebase site

**Comment by vaheqelyan** [comment]
tried this template https://github.com/sveltejs/sapper-template-webpack (`svelte-grid@3.3.1` works), 
so it looks like it works for both webpack and rollup

**Comment by vaheqelyan** [comment]
Optional chaining' has been replaced. in addition, you no longer need to access the element using the optional chain operator

```svelte
// no need
<Grid let:item>{item?.fixed}</Grid>
// ok
<Grid let:item>{item.fixed}</Grid>
```

**Comment by evdama** [comment]
excellent, thanks again a lot for your time and effort 👍 
[](https://media.giphy.com/media/l2Sqir5ZxfoS27EvS/giphy.gif)

**Comment by michaelcuneo** [comment]
For some reason, this issue isn't solve for me ... 

I updated svelte-grid to the latest. 3.1.1.

Because I'm using npm, I added 
```
    "preinstall": "npx npm-force-resolutions" // added to scripts.
```
and
```
"resolutions": {
    "acorn": "8.0.1"
  },
```
I remove node_modules.
Ran `npx npm-force-resolutions`, and `npx npm-force-resolutions -g` just to be sure... 

I then ran `npm install`

Got back into my project and it's identical.

```
webpack:///./node_modules/svelte-grid/src/index.svelte?:1
throw new Error("Module parse failed: Unexpected token (133:36)\nFile was processed with these loaders:\n * ./node_modules/svelte-loader/index.js\nYou may need an additional loader to handle the result of these loaders.\n| \t\t{\n| \t\t\tid: item.id,\n> \t\t\tresizable: item[getComputedCols]?.resizable,\n| \t\t\tdraggable: item[getComputedCols]?.draggable,\n| \t\t\txPerPx,");
^

Error: Module parse failed: Unexpected token (133:36)
File was processed with these loaders:
 * ./node_modules/svelte-loader/index.js
You may need an additional loader to handle the result of these loaders.
|               {
|                       id: item.id,
>                       resizable: item[getComputedCols]?.resizable,
|                       draggable: item[getComputedCols]?.draggable,
|                       xPerPx,
    at eval (webpack:///./node_modules/svelte-grid/src/index.svelte?:1:7)
    at Object../node_modules/svelte-grid/src/index.svelte (/mnt/store/share/thealbion.com.au/__sapper__/dev/server/server.js:16884:1)
    at __webpack_require__ (/mnt/store/share/thealbion.com.au/__sapper__/dev/server/server.js:27:30)
    at eval (webpack:///./src/routes/gallery.svelte?:4:69)
    at Module../src/routes/gallery.svelte (/mnt/store/share/thealbion.com.au/__sapper__/dev/server/server.js:17752:1)
    at __webpack_require__ (/mnt/store/share/thealbion.com.au/__sapper__/dev/server/server.js:27:30)
    at eval (webpack:///./src/node_modules/@sapper/internal/manifest-server.mjs?:12:80)
    at Module../src/node_modules/@sapper/internal/manifest-server.mjs (/mnt/store/share/thealbion.com.au/__sapper__/dev/server/server.js:17584:1)
    at __webpack_require__ (/mnt/store/share/thealbion.com.au/__sapper__/dev/server/server.js:27:30)
    at eval (webpack:///./src/node_modules/@sapper/server.mjs?:7:83)
```

**Comment by michaelcuneo** [comment]
Ahh my mistake, I upgraded to the wrong version. I have now upgraded to Svelte-Grid  3.3.1.

And now I am further into a new error.

`500 - Failed to Fetch dynamically imported module: http://192.168.0.10:3000/routes/index.svelte`

Hmmm

**Comment by michaelcuneo** [comment]
100% fine now. I forgot to remove packacge-lock.

**Comment by vaheqelyan** [comment]
nice :+1:
